version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
      - echo "Installing dependencies or performing any pre-build steps"

  pre_build:
    commands:
      - echo "Executing pre-build steps if needed"

  build:
    commands:
      - echo "Executing build steps"

files:
  - '**/*'
    destination: /var/www/html/test/

permissions:
  - object: /var/www/html/test/
    pattern: "**"
    owner: www-data
    group: www-data
